"""
REPORT GENERATOR — Automated analysis report generation.

Creates structured reports from the Cognitive Market Engine's analysis:
- Event analysis reports
- Daily market summaries
- Risk assessment reports
- Model performance reports
- System health reports
"""

import json
from datetime import datetime
from typing import Dict, List, Optional


class ReportGenerator:
    """
    Automated report generator for the Cognitive Market Engine.
    
    Creates Markdown and JSON reports from system analysis data.
    """
    
    def __init__(self, storage=None, feedback_loop=None,
                 correlation_engine=None, geopolitical_scorer=None):
        """
        Args:
            storage: DatabaseManager
            feedback_loop: FeedbackLoop
            correlation_engine: CorrelationEngine
            geopolitical_scorer: GeopoliticalRiskScorer
        """
        self.storage = storage
        self.feedback_loop = feedback_loop
        self.correlation_engine = correlation_engine
        self.geopolitical_scorer = geopolitical_scorer
        print("[REPORTS] Report generator initialized")
    
    def generate_event_report(self, event_data: Dict,
                               cognitive_result: Dict = None,
                               scenarios: Dict = None) -> str:
        """
        Generate a detailed event analysis report.
        
        Args:
            event_data: Parsed event data
            cognitive_result: Cognitive system analysis
            scenarios: Generated scenarios
            
        Returns:
            Markdown report string
        """
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        lines = [
            f"# Event Analysis Report",
            f"**Generated:** {now}",
            "",
            "---",
            "",
            "## Event Summary",
            f"- **Source:** {event_data.get('source', 'Unknown')}",
            f"- **Text:** {event_data.get('raw_text', '')[:300]}",
            f"- **Ambiguity:** {event_data.get('ambiguity_score', 0):.2f}",
            f"- **Certainty:** {event_data.get('certainty_score', 0):.2f}",
            "",
        ]
        
        # Cognitive analysis
        if cognitive_result:
            lines.extend([
                "## Cognitive Analysis",
                "",
            ])
            
            if "interpretations" in cognitive_result:
                lines.append("### Participant Interpretations")
                for interp in cognitive_result["interpretations"]:
                    name = interp.get("participant", "Unknown")
                    direction = interp.get("direction", "neutral")
                    confidence = interp.get("confidence", 0)
                    lines.append(f"- **{name}:** {direction} "
                               f"(confidence: {confidence:.1%})")
                lines.append("")
            
            if "consensus" in cognitive_result:
                c = cognitive_result["consensus"]
                lines.extend([
                    "### Market Consensus",
                    f"- Direction: **{c.get('direction', 'N/A')}**",
                    f"- Strength: {c.get('strength', 0):.2f}",
                    f"- Agreement: {c.get('agreement', 0):.1%}",
                    "",
                ])
        
        # Scenarios
        if scenarios:
            lines.extend([
                "## Scenario Analysis",
                "",
            ])
            
            scenario_list = scenarios.get("scenarios", [])
            for i, s in enumerate(scenario_list[:5], 1):
                lines.extend([
                    f"### Scenario {i}: {s.get('name', 'Unknown')}",
                    f"- Probability: {s.get('probability', 0):.1%}",
                    f"- Direction: {s.get('direction', 'N/A')}",
                    f"- Expected Move: {s.get('expected_move', 0):.2%}",
                    f"- Description: {s.get('description', '')}",
                    "",
                ])
        
        lines.extend([
            "---",
            f"*Report generated by Cognitive Market Engine*",
        ])
        
        return "\n".join(lines)
    
    def generate_daily_summary(self) -> str:
        """Generate a daily market summary report."""
        now = datetime.now()
        date_str = now.strftime("%Y-%m-%d")
        
        lines = [
            f"# Daily Market Summary — {date_str}",
            f"**Generated:** {now.strftime('%H:%M:%S')}",
            "",
            "---",
            "",
        ]
        
        # Model performance
        if self.feedback_loop:
            report = self.feedback_loop.get_credibility_report()
            overall = report.get("overall", {})
            
            lines.extend([
                "## Model Performance",
                f"- Total Validated: {overall.get('total_validated', 0)}",
                f"- Overall Accuracy: {overall.get('overall_accuracy', 0):.1%}",
                "",
                "### Model Rankings",
            ])
            
            for name, model in report.get("models", {}).items():
                lines.append(
                    f"- **{name}:** accuracy={model.get('accuracy_ema', 0):.1%}, "
                    f"weight={model.get('weight', 1.0):.2f}"
                )
            lines.append("")
        
        # Correlation state
        if self.correlation_engine:
            try:
                if hasattr(self.correlation_engine, "detect_anomalies"):
                    anomalies = self.correlation_engine.detect_anomalies()
                    if anomalies:
                        lines.extend([
                            "## Correlation Anomalies",
                        ])
                        for a in anomalies:
                            lines.append(f"- ⚠️ {a.get('message', '')}")
                        lines.append("")
            except Exception:
                pass
        
        # Geopolitical risk
        if self.geopolitical_scorer:
            risk = self.geopolitical_scorer.get_global_risk_index()
            lines.extend([
                "## Geopolitical Risk",
                f"- Risk Index: **{risk.get('risk_index', 0):.2f}**",
                f"- Level: **{risk.get('level', 'N/A')}**",
                f"- Active Events: {risk.get('active_events', 0)}",
                "",
            ])
            
            for hotspot in risk.get("hotspots", []):
                lines.append(
                    f"- {hotspot['region']}: risk={hotspot['risk']:.2f}, "
                    f"events={hotspot['events']}"
                )
            lines.append("")
        
        # Storage stats
        if self.storage and hasattr(self.storage, "get_stats"):
            try:
                stats = self.storage.get_stats()
                lines.extend([
                    "## System Statistics",
                    f"- Total News Events: {stats.get('news_events', 0)}",
                    f"- Total Signals: {stats.get('trading_signals', 0)}",
                    f"- Validation Records: {stats.get('validation_records', 0)}",
                    "",
                ])
            except Exception:
                pass
        
        lines.extend([
            "---",
            "*Report generated by Cognitive Market Engine*",
        ])
        
        return "\n".join(lines)
    
    def generate_risk_report(self) -> str:
        """Generate a risk assessment report."""
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        lines = [
            f"# Risk Assessment Report",
            f"**Generated:** {now}",
            "",
            "---",
            "",
        ]
        
        # Geopolitical
        if self.geopolitical_scorer:
            risk = self.geopolitical_scorer.get_global_risk_index()
            lines.extend([
                "## Geopolitical Risk Assessment",
                f"- **Global Risk Index:** {risk.get('risk_index', 0):.3f}",
                f"- **Alert Level:** {risk.get('level', 'unknown').upper()}",
                "",
                "### Regional Hotspots",
            ])
            
            for h in risk.get("hotspots", []):
                lines.append(f"| {h['region']} | {h['risk']:.3f} | {h['events']} events |")
            lines.append("")
            
            most_affected = risk.get("most_affected_assets", [])
            if most_affected:
                lines.extend([
                    "### Most Affected Assets",
                    ", ".join(most_affected),
                    "",
                ])
        
        # Correlation risk
        if self.correlation_engine:
            try:
                if hasattr(self.correlation_engine, "get_systemic_risk"):
                    sys_risk = self.correlation_engine.get_systemic_risk()
                    lines.extend([
                        "## Systemic Risk Indicators",
                        f"- Systemic Risk Score: {sys_risk:.3f}",
                        "",
                    ])
            except Exception:
                pass
        
        # Model confidence
        if self.feedback_loop:
            weights = self.feedback_loop.get_ensemble_weights()
            lines.extend([
                "## Model Confidence Assessment",
            ])
            for name, weight in sorted(weights.items(), key=lambda x: -x[1]):
                bar = "█" * int(weight * 20)
                lines.append(f"- {name}: {bar} ({weight:.1%})")
            lines.append("")
        
        lines.extend([
            "---",
            "*Report generated by Cognitive Market Engine*",
        ])
        
        return "\n".join(lines)
    
    def generate_system_health(self, pipeline=None) -> str:
        """Generate system health report."""
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        lines = [
            f"# System Health Report",
            f"**Generated:** {now}",
            "",
            "---",
            "",
        ]
        
        # Pipeline status
        if pipeline:
            metrics = pipeline.get_metrics()
            status = metrics.get("pipeline_status", "unknown")
            status_icon = "🟢" if status == "running" else "🔴"
            
            lines.extend([
                "## Pipeline Status",
                f"- Status: {status_icon} **{status}**",
                f"- Events Processed: {metrics.get('events_processed', 0)}",
                f"- Average Latency: {metrics.get('avg_latency_ms', 0):.1f} ms",
                f"- Errors: {metrics.get('errors', 0)}",
                f"- Last Processed: {metrics.get('last_processed', 'N/A')}",
                "",
            ])
        
        # Module availability
        lines.extend([
            "## Module Status",
            f"- Storage: {'🟢' if self.storage else '🔴'}",
            f"- Feedback Loop: {'🟢' if self.feedback_loop else '🔴'}",
            f"- Correlation Engine: {'🟢' if self.correlation_engine else '🔴'}",
            f"- Geopolitical Scorer: {'🟢' if self.geopolitical_scorer else '🔴'}",
            "",
        ])
        
        # Check dependencies
        lines.append("## Dependency Status")
        deps = [
            ("spacy", "NLP Engine"),
            ("transformers", "Deep NLP"),
            ("torch", "ML Models"),
            ("networkx", "Knowledge Graph"),
            ("streamlit", "Dashboard"),
            ("openai", "LLM Analyzer"),
            ("praw", "Reddit API"),
            ("tweepy", "Twitter API"),
            ("pandas", "Data Analysis"),
            ("numpy", "Numerical"),
        ]
        
        for mod, desc in deps:
            try:
                __import__(mod)
                lines.append(f"- {desc} ({mod}): 🟢 installed")
            except ImportError:
                lines.append(f"- {desc} ({mod}): 🟡 not installed")
        
        lines.extend(["", "---", "*Report generated by Cognitive Market Engine*"])
        
        return "\n".join(lines)
    
    def save_report(self, report: str, filename: str = None,
                    output_dir: str = "reports"):
        """Save report to file."""
        import os
        
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"report_{timestamp}.md"
        
        os.makedirs(output_dir, exist_ok=True)
        filepath = os.path.join(output_dir, filename)
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report)
        
        print(f"[REPORTS] Saved: {filepath}")
        return filepath
