"""
BACKTESTING FRAMEWORK — Cognitive Market Engine

Purpose:
Historical event replay engine for measuring theoretical P&L,
signal accuracy, and model performance over time.

This is NOT a production trading system — it's a research tool for
validating whether the cognitive engine's predictions would have
been profitable historically.

Components:
1. EventReplayEngine — replays historical news + price data
2. PositionTracker — tracks simulated portfolio
3. PerformanceAnalytics — Sharpe, Sortino, drawdown, win rate
4. BacktestRunner — orchestrates end-to-end backtests
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Callable
from datetime import datetime, timedelta
from enum import Enum
import statistics
import math
import json
import os
import logging

logger = logging.getLogger("cme.backtesting")


# ============================================================
# DATA STRUCTURES
# ============================================================

class TradeAction(str, Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE = "close"


@dataclass
class HistoricalEvent:
    """A single historical news event with associated market data."""
    event_id: str
    timestamp: datetime
    headline: str
    content: str
    source: str
    event_type: str  # rate_decision, earnings, geopolitical, etc.
    
    # Market data at the time of the event
    price_at_event: float
    price_1h_after: float
    price_4h_after: float
    price_24h_after: float
    
    # Realized volatility around event
    vol_before: float = 0.0
    vol_after: float = 0.0
    
    # Optional metadata
    metadata: Dict = field(default_factory=dict)


@dataclass
class SignalRecord:
    """A signal generated by the engine during backtesting."""
    timestamp: datetime
    event_id: str
    action: TradeAction
    direction: str  # "bullish", "bearish", "neutral"
    confidence: float
    position_size: float  # fraction of capital
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    reasoning: str = ""


@dataclass
class TradeRecord:
    """A completed trade (entry + exit)."""
    entry_time: datetime
    exit_time: datetime
    direction: str
    entry_price: float
    exit_price: float
    position_size: float
    pnl: float
    pnl_pct: float
    holding_period: timedelta
    signal_confidence: float
    event_id: str
    exit_reason: str  # "take_profit", "stop_loss", "timeout", "signal_reversal"


@dataclass
class PortfolioSnapshot:
    """Portfolio state at a point in time."""
    timestamp: datetime
    capital: float
    unrealized_pnl: float
    realized_pnl: float
    num_open_positions: int
    total_trades: int
    equity: float  # capital + unrealized


@dataclass
class BacktestResult:
    """Complete backtest output."""
    start_date: datetime
    end_date: datetime
    initial_capital: float
    final_capital: float
    total_trades: int
    winning_trades: int
    losing_trades: int
    
    # Performance metrics
    total_return: float
    annualized_return: float
    sharpe_ratio: float
    sortino_ratio: float
    max_drawdown: float
    max_drawdown_duration: timedelta
    win_rate: float
    profit_factor: float
    avg_win: float
    avg_loss: float
    avg_holding_period: timedelta
    
    # Signal quality
    directional_accuracy: float
    avg_signal_confidence: float
    confidence_calibration: float  # correlation between confidence and accuracy
    
    # Detailed records
    trades: List[TradeRecord] = field(default_factory=list)
    equity_curve: List[PortfolioSnapshot] = field(default_factory=list)
    
    def to_dict(self) -> Dict:
        return {
            "period": f"{self.start_date.date()} to {self.end_date.date()}",
            "initial_capital": self.initial_capital,
            "final_capital": round(self.final_capital, 2),
            "total_return": f"{self.total_return:.2%}",
            "annualized_return": f"{self.annualized_return:.2%}",
            "sharpe_ratio": round(self.sharpe_ratio, 3),
            "sortino_ratio": round(self.sortino_ratio, 3),
            "max_drawdown": f"{self.max_drawdown:.2%}",
            "total_trades": self.total_trades,
            "win_rate": f"{self.win_rate:.2%}",
            "profit_factor": round(self.profit_factor, 3),
            "directional_accuracy": f"{self.directional_accuracy:.2%}",
            "avg_holding_period": str(self.avg_holding_period),
        }


# ============================================================
# POSITION TRACKER
# ============================================================

class PositionTracker:
    """
    Tracks simulated portfolio during backtesting.
    
    Supports:
    - Long and short positions
    - Stop loss and take profit
    - Position sizing limits
    - Equity curve tracking
    """
    
    def __init__(self, initial_capital: float = 100_000.0, max_position_pct: float = 0.10):
        self.initial_capital = initial_capital
        self.capital = initial_capital
        self.max_position_pct = max_position_pct
        
        self.open_positions: List[Dict] = []
        self.closed_trades: List[TradeRecord] = []
        self.equity_curve: List[PortfolioSnapshot] = []
        
        self._peak_equity = initial_capital
        self._max_drawdown = 0.0
        self._drawdown_start: Optional[datetime] = None
        self._max_drawdown_duration = timedelta(0)
    
    def open_position(
        self,
        timestamp: datetime,
        direction: str,
        price: float,
        size_pct: float,
        stop_loss: Optional[float],
        take_profit: Optional[float],
        event_id: str,
        confidence: float
    ) -> bool:
        """Open a new position. Returns True if successfully opened."""
        # Enforce max position size
        actual_size = min(size_pct, self.max_position_pct)
        position_value = self.capital * actual_size
        
        if position_value <= 0 or self.capital <= 0:
            return False
        
        self.open_positions.append({
            "entry_time": timestamp,
            "direction": direction,
            "entry_price": price,
            "size_pct": actual_size,
            "position_value": position_value,
            "stop_loss": stop_loss,
            "take_profit": take_profit,
            "event_id": event_id,
            "confidence": confidence,
        })
        return True
    
    def check_exits(self, timestamp: datetime, current_price: float, max_holding: timedelta = timedelta(hours=24)):
        """Check all open positions for stop/target/timeout exits."""
        still_open = []
        
        for pos in self.open_positions:
            exit_reason = None
            exit_price = current_price
            
            # Check timeout
            if timestamp - pos["entry_time"] >= max_holding:
                exit_reason = "timeout"
            
            # Check stop loss
            if pos["stop_loss"] is not None:
                if pos["direction"] == "bullish" and current_price <= pos["stop_loss"]:
                    exit_reason = "stop_loss"
                    exit_price = pos["stop_loss"]
                elif pos["direction"] == "bearish" and current_price >= pos["stop_loss"]:
                    exit_reason = "stop_loss"
                    exit_price = pos["stop_loss"]
            
            # Check take profit
            if pos["take_profit"] is not None:
                if pos["direction"] == "bullish" and current_price >= pos["take_profit"]:
                    exit_reason = "take_profit"
                    exit_price = pos["take_profit"]
                elif pos["direction"] == "bearish" and current_price <= pos["take_profit"]:
                    exit_reason = "take_profit"
                    exit_price = pos["take_profit"]
            
            if exit_reason:
                self._close_position(pos, timestamp, exit_price, exit_reason)
            else:
                still_open.append(pos)
        
        self.open_positions = still_open
    
    def _close_position(self, pos: Dict, timestamp: datetime, exit_price: float, reason: str):
        """Close a position and record the trade."""
        if pos["direction"] == "bullish":
            pnl_pct = (exit_price - pos["entry_price"]) / pos["entry_price"]
        else:
            pnl_pct = (pos["entry_price"] - exit_price) / pos["entry_price"]
        
        pnl = pos["position_value"] * pnl_pct
        self.capital += pnl
        
        trade = TradeRecord(
            entry_time=pos["entry_time"],
            exit_time=timestamp,
            direction=pos["direction"],
            entry_price=pos["entry_price"],
            exit_price=exit_price,
            position_size=pos["size_pct"],
            pnl=round(pnl, 2),
            pnl_pct=round(pnl_pct, 6),
            holding_period=timestamp - pos["entry_time"],
            signal_confidence=pos["confidence"],
            event_id=pos["event_id"],
            exit_reason=reason,
        )
        self.closed_trades.append(trade)
    
    def snapshot(self, timestamp: datetime, current_price: float) -> PortfolioSnapshot:
        """Take a portfolio snapshot."""
        unrealized = 0.0
        for pos in self.open_positions:
            if pos["direction"] == "bullish":
                unrealized += pos["position_value"] * (
                    (current_price - pos["entry_price"]) / pos["entry_price"]
                )
            else:
                unrealized += pos["position_value"] * (
                    (pos["entry_price"] - current_price) / pos["entry_price"]
                )
        
        equity = self.capital + unrealized
        realized = sum(t.pnl for t in self.closed_trades)
        
        # Track drawdown
        if equity > self._peak_equity:
            self._peak_equity = equity
            self._drawdown_start = None
        else:
            dd = (self._peak_equity - equity) / self._peak_equity
            if dd > self._max_drawdown:
                self._max_drawdown = dd
            if self._drawdown_start is None:
                self._drawdown_start = timestamp
            else:
                dd_duration = timestamp - self._drawdown_start
                if dd_duration > self._max_drawdown_duration:
                    self._max_drawdown_duration = dd_duration
        
        snap = PortfolioSnapshot(
            timestamp=timestamp,
            capital=round(self.capital, 2),
            unrealized_pnl=round(unrealized, 2),
            realized_pnl=round(realized, 2),
            num_open_positions=len(self.open_positions),
            total_trades=len(self.closed_trades),
            equity=round(equity, 2),
        )
        self.equity_curve.append(snap)
        return snap


# ============================================================
# PERFORMANCE ANALYTICS
# ============================================================

class PerformanceAnalytics:
    """
    Computes performance metrics from backtest results.
    
    Metrics:
    - Sharpe Ratio (annualized, risk-free = 0)
    - Sortino Ratio (downside deviation only)
    - Max Drawdown and duration
    - Win Rate, Profit Factor
    - Average Win/Loss
    - Confidence calibration
    """
    
    @staticmethod
    def compute(
        trades: List[TradeRecord],
        equity_curve: List[PortfolioSnapshot],
        initial_capital: float,
        risk_free_rate: float = 0.0
    ) -> Dict:
        """Compute all performance metrics."""
        if not trades:
            return {
                "total_trades": 0,
                "message": "No trades executed"
            }
        
        # Basic stats
        pnls = [t.pnl for t in trades]
        pnl_pcts = [t.pnl_pct for t in trades]
        winners = [p for p in pnls if p > 0]
        losers = [p for p in pnls if p < 0]
        
        total_trades = len(trades)
        winning_trades = len(winners)
        losing_trades = len(losers)
        win_rate = winning_trades / total_trades if total_trades > 0 else 0.0
        
        # P&L
        total_pnl = sum(pnls)
        total_return = total_pnl / initial_capital
        
        avg_win = statistics.mean(winners) if winners else 0.0
        avg_loss = statistics.mean(losers) if losers else 0.0
        
        gross_profit = sum(winners) if winners else 0.0
        gross_loss = abs(sum(losers)) if losers else 1.0
        profit_factor = gross_profit / gross_loss if gross_loss > 0 else float('inf')
        
        # Holding period
        holding_periods = [t.holding_period for t in trades]
        avg_holding = sum(holding_periods, timedelta()) / len(holding_periods)
        
        # Annualized return
        if len(equity_curve) >= 2:
            total_days = (equity_curve[-1].timestamp - equity_curve[0].timestamp).days
            total_days = max(total_days, 1)
            annualized_return = (1 + total_return) ** (365 / total_days) - 1
        else:
            annualized_return = total_return
        
        # Sharpe Ratio (annualized)
        if len(pnl_pcts) > 1:
            mean_ret = statistics.mean(pnl_pcts)
            std_ret = statistics.stdev(pnl_pcts)
            # Assume ~252 trading events per year
            sharpe = (mean_ret - risk_free_rate / 252) / std_ret * math.sqrt(252) if std_ret > 0 else 0.0
        else:
            sharpe = 0.0
        
        # Sortino Ratio (downside deviation only)
        downside_returns = [r for r in pnl_pcts if r < 0]
        if len(downside_returns) > 1:
            downside_dev = statistics.stdev(downside_returns)
            mean_ret = statistics.mean(pnl_pcts)
            sortino = (mean_ret - risk_free_rate / 252) / downside_dev * math.sqrt(252) if downside_dev > 0 else 0.0
        else:
            sortino = sharpe  # No downside → same as Sharpe
        
        # Max drawdown from equity curve
        max_dd = 0.0
        peak = initial_capital
        max_dd_duration = timedelta(0)
        dd_start = None
        
        for snap in equity_curve:
            if snap.equity > peak:
                peak = snap.equity
                dd_start = None
            else:
                dd = (peak - snap.equity) / peak
                if dd > max_dd:
                    max_dd = dd
                if dd_start is None:
                    dd_start = snap.timestamp
                elif snap.timestamp - dd_start > max_dd_duration:
                    max_dd_duration = snap.timestamp - dd_start
        
        # Directional accuracy
        direction_correct = sum(
            1 for t in trades
            if (t.direction == "bullish" and t.pnl > 0) or
               (t.direction == "bearish" and t.pnl > 0)
        )
        directional_accuracy = direction_correct / total_trades
        
        # Confidence calibration: do high-confidence trades win more?
        if total_trades >= 5:
            high_conf = [t for t in trades if t.signal_confidence >= 0.6]
            low_conf = [t for t in trades if t.signal_confidence < 0.6]
            high_wr = sum(1 for t in high_conf if t.pnl > 0) / max(len(high_conf), 1)
            low_wr = sum(1 for t in low_conf if t.pnl > 0) / max(len(low_conf), 1)
            calibration = high_wr - low_wr  # Positive = well calibrated
        else:
            calibration = 0.0
        
        avg_confidence = statistics.mean([t.signal_confidence for t in trades])
        
        final_capital = equity_curve[-1].equity if equity_curve else initial_capital + total_pnl
        
        return {
            "start_date": trades[0].entry_time,
            "end_date": trades[-1].exit_time,
            "initial_capital": initial_capital,
            "final_capital": round(final_capital, 2),
            "total_trades": total_trades,
            "winning_trades": winning_trades,
            "losing_trades": losing_trades,
            "total_return": round(total_return, 6),
            "annualized_return": round(annualized_return, 6),
            "sharpe_ratio": round(sharpe, 4),
            "sortino_ratio": round(sortino, 4),
            "max_drawdown": round(max_dd, 6),
            "max_drawdown_duration": max_dd_duration,
            "win_rate": round(win_rate, 4),
            "profit_factor": round(profit_factor, 4),
            "avg_win": round(avg_win, 2),
            "avg_loss": round(avg_loss, 2),
            "avg_holding_period": avg_holding,
            "directional_accuracy": round(directional_accuracy, 4),
            "avg_signal_confidence": round(avg_confidence, 4),
            "confidence_calibration": round(calibration, 4),
        }


# ============================================================
# EVENT REPLAY ENGINE
# ============================================================

class EventReplayEngine:
    """
    Replays historical events through the cognitive engine.
    
    Supports:
    - Loading events from JSON files
    - Sequential chronological replay
    - Injecting custom signal generators
    """
    
    def __init__(self):
        self.events: List[HistoricalEvent] = []
    
    def load_events_from_json(self, filepath: str) -> int:
        """Load historical events from a JSON file. Returns count loaded."""
        if not os.path.exists(filepath):
            logger.warning(f"Event file not found: {filepath}")
            return 0
        
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        for item in data:
            try:
                event = HistoricalEvent(
                    event_id=item.get("event_id", f"evt_{len(self.events)}"),
                    timestamp=datetime.fromisoformat(item["timestamp"]),
                    headline=item["headline"],
                    content=item.get("content", item["headline"]),
                    source=item.get("source", "unknown"),
                    event_type=item.get("event_type", "generic"),
                    price_at_event=float(item["price_at_event"]),
                    price_1h_after=float(item.get("price_1h_after", item["price_at_event"])),
                    price_4h_after=float(item.get("price_4h_after", item["price_at_event"])),
                    price_24h_after=float(item.get("price_24h_after", item["price_at_event"])),
                    vol_before=float(item.get("vol_before", 0.0)),
                    vol_after=float(item.get("vol_after", 0.0)),
                    metadata=item.get("metadata", {}),
                )
                self.events.append(event)
            except (KeyError, ValueError) as e:
                logger.warning(f"Skipping malformed event: {e}")
        
        # Sort chronologically
        self.events.sort(key=lambda e: e.timestamp)
        logger.info(f"Loaded {len(self.events)} historical events")
        return len(self.events)
    
    def add_event(self, event: HistoricalEvent):
        """Add a single event and maintain chronological order."""
        self.events.append(event)
        self.events.sort(key=lambda e: e.timestamp)
    
    def get_events_in_range(
        self,
        start: datetime,
        end: datetime
    ) -> List[HistoricalEvent]:
        """Get events within a date range."""
        return [e for e in self.events if start <= e.timestamp <= end]
    
    def replay(
        self,
        signal_generator: Callable[[HistoricalEvent], Optional[SignalRecord]],
        start: Optional[datetime] = None,
        end: Optional[datetime] = None
    ) -> List[Tuple[HistoricalEvent, Optional[SignalRecord]]]:
        """
        Replay events through a signal generator function.
        
        Args:
            signal_generator: function(HistoricalEvent) -> Optional[SignalRecord]
            start: optional start date filter
            end: optional end date filter
            
        Returns:
            List of (event, signal) pairs
        """
        events = self.events
        if start:
            events = [e for e in events if e.timestamp >= start]
        if end:
            events = [e for e in events if e.timestamp <= end]
        
        results = []
        for event in events:
            try:
                signal = signal_generator(event)
                results.append((event, signal))
            except Exception as e:
                logger.error(f"Signal generation failed for {event.event_id}: {e}")
                results.append((event, None))
        
        return results


# ============================================================
# BACKTEST RUNNER
# ============================================================

class BacktestRunner:
    """
    Orchestrates end-to-end backtesting.
    
    Workflow:
    1. Load historical events
    2. For each event, generate signals via user-provided callback
    3. Execute signals in simulated portfolio
    4. Track positions with stop/target/timeout
    5. Compute performance analytics
    """
    
    def __init__(
        self,
        initial_capital: float = 100_000.0,
        max_position_pct: float = 0.10,
        default_stop_pct: float = 0.02,
        default_target_pct: float = 0.04,
        max_holding_hours: int = 24,
    ):
        self.initial_capital = initial_capital
        self.max_position_pct = max_position_pct
        self.default_stop_pct = default_stop_pct
        self.default_target_pct = default_target_pct
        self.max_holding = timedelta(hours=max_holding_hours)
        
        self.replay_engine = EventReplayEngine()
        self.tracker = PositionTracker(initial_capital, max_position_pct)
        self.analytics = PerformanceAnalytics()
    
    def run(
        self,
        signal_generator: Callable[[HistoricalEvent], Optional[SignalRecord]],
        snapshot_interval: timedelta = timedelta(hours=1),
    ) -> BacktestResult:
        """
        Run a complete backtest.
        
        Args:
            signal_generator: function(HistoricalEvent) -> Optional[SignalRecord]
            snapshot_interval: how often to snapshot portfolio
            
        Returns:
            BacktestResult with full performance analysis
        """
        if not self.replay_engine.events:
            logger.warning("No events loaded — cannot run backtest")
            return self._empty_result()
        
        events = self.replay_engine.events
        last_snapshot_time = events[0].timestamp
        
        for event in events:
            current_price = event.price_at_event
            
            # Check exits on existing positions
            self.tracker.check_exits(event.timestamp, current_price, self.max_holding)
            
            # Generate signal
            try:
                signal = signal_generator(event)
            except Exception as e:
                logger.error(f"Signal generator error: {e}")
                signal = None
            
            # Execute signal
            if signal and signal.action in (TradeAction.BUY, TradeAction.SELL):
                direction = "bullish" if signal.action == TradeAction.BUY else "bearish"
                
                stop = signal.stop_loss
                target = signal.take_profit
                
                # Default stop/target if not provided
                if stop is None:
                    if direction == "bullish":
                        stop = current_price * (1 - self.default_stop_pct)
                    else:
                        stop = current_price * (1 + self.default_stop_pct)
                
                if target is None:
                    if direction == "bullish":
                        target = current_price * (1 + self.default_target_pct)
                    else:
                        target = current_price * (1 - self.default_target_pct)
                
                self.tracker.open_position(
                    timestamp=event.timestamp,
                    direction=direction,
                    price=current_price,
                    size_pct=signal.position_size,
                    stop_loss=stop,
                    take_profit=target,
                    event_id=event.event_id,
                    confidence=signal.confidence,
                )
            
            # Periodic snapshot
            if event.timestamp - last_snapshot_time >= snapshot_interval:
                self.tracker.snapshot(event.timestamp, current_price)
                last_snapshot_time = event.timestamp
        
        # Close any remaining positions at last known price
        if events:
            last_price = events[-1].price_24h_after
            last_time = events[-1].timestamp + timedelta(hours=24)
            for pos in list(self.tracker.open_positions):
                self.tracker._close_position(pos, last_time, last_price, "backtest_end")
            self.tracker.open_positions.clear()
            self.tracker.snapshot(last_time, last_price)
        
        # Compute analytics
        metrics = self.analytics.compute(
            self.tracker.closed_trades,
            self.tracker.equity_curve,
            self.initial_capital,
        )
        
        if metrics.get("total_trades", 0) == 0:
            return self._empty_result()
        
        return BacktestResult(
            start_date=metrics["start_date"],
            end_date=metrics["end_date"],
            initial_capital=self.initial_capital,
            final_capital=metrics["final_capital"],
            total_trades=metrics["total_trades"],
            winning_trades=metrics["winning_trades"],
            losing_trades=metrics["losing_trades"],
            total_return=metrics["total_return"],
            annualized_return=metrics["annualized_return"],
            sharpe_ratio=metrics["sharpe_ratio"],
            sortino_ratio=metrics["sortino_ratio"],
            max_drawdown=metrics["max_drawdown"],
            max_drawdown_duration=metrics["max_drawdown_duration"],
            win_rate=metrics["win_rate"],
            profit_factor=metrics["profit_factor"],
            avg_win=metrics["avg_win"],
            avg_loss=metrics["avg_loss"],
            avg_holding_period=metrics["avg_holding_period"],
            directional_accuracy=metrics["directional_accuracy"],
            avg_signal_confidence=metrics["avg_signal_confidence"],
            confidence_calibration=metrics["confidence_calibration"],
            trades=self.tracker.closed_trades,
            equity_curve=self.tracker.equity_curve,
        )
    
    def _empty_result(self) -> BacktestResult:
        """Return empty result when no trades occurred."""
        now = datetime.utcnow()
        return BacktestResult(
            start_date=now,
            end_date=now,
            initial_capital=self.initial_capital,
            final_capital=self.initial_capital,
            total_trades=0,
            winning_trades=0,
            losing_trades=0,
            total_return=0.0,
            annualized_return=0.0,
            sharpe_ratio=0.0,
            sortino_ratio=0.0,
            max_drawdown=0.0,
            max_drawdown_duration=timedelta(0),
            win_rate=0.0,
            profit_factor=0.0,
            avg_win=0.0,
            avg_loss=0.0,
            avg_holding_period=timedelta(0),
            directional_accuracy=0.0,
            avg_signal_confidence=0.0,
            confidence_calibration=0.0,
        )
    
    def save_results(self, result: BacktestResult, filepath: str):
        """Save backtest results to JSON."""
        output = result.to_dict()
        output["trades"] = [
            {
                "entry_time": t.entry_time.isoformat(),
                "exit_time": t.exit_time.isoformat(),
                "direction": t.direction,
                "entry_price": t.entry_price,
                "exit_price": t.exit_price,
                "pnl": t.pnl,
                "pnl_pct": f"{t.pnl_pct:.4%}",
                "confidence": t.signal_confidence,
                "exit_reason": t.exit_reason,
            }
            for t in result.trades
        ]
        
        os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(output, f, indent=2, default=str)
        
        logger.info(f"Backtest results saved to {filepath}")
